# Generated by Django 4.2.5 on 2023-09-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'активен'), ('blocked', 'заблокирован')], default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
