# Generated by Django 4.2.5 on 2023-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='')),
                ('text', models.TextField(verbose_name='')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('views_count', models.IntegerField(default=0, verbose_name='')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
