# Generated by Django 4.2.5 on 2023-09-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='desription',
            new_name='description',
        ),
    ]
