# Generated by Django 4.2.5 on 2023-09-25 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailings.mailing', verbose_name='Рассылка'),
            preserve_default=False,
        ),
    ]
