# Generated by Django 4.2.5 on 2023-09-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_mailinglog_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing_date',
            field=models.DateField(verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing_time',
            field=models.TimeField(verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='server_ans',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ сервера'),
        ),
    ]
