# Generated by Django 4.2.5 on 2023-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0008_alter_mailinglog_options_mailinglog_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
    ]
